CREATE OR REPLACE TABLE USER_TB (ID NUMBER PRIMARY KEY NOT NULL, first_name VARCHAR(200) NOT NULL, last_name VARCHAR(200) NOT NULL, email VARCHAR(200) NOT NULL, birthday VARCHAR(200) NOT NULL, login VARCHAR(200) NOT NULL, password VARCHAR(200) NOT NULL, phone VARCHAR(200) NOT NULL);
CREATE OR REPLACE TABLE CAR_TB (ID NUMBER PRIMARY KEY NOT NULL, year_field int NOT NULL, license_plate VARCHAR(200) NOT NULL, model VARCHAR(200) NOT NULL, color VARCHAR(200) NOT NULL, user_id int, FOREIGN KEY (user_id) REFERENCES USER_TB(id));

CREATE SEQUENCE SEQ_CAR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;

ALTER TABLE USER_TB ADD CONSTRAINT user_unique_email UNIQUE (email);
ALTER TABLE USER_TB ADD CONSTRAINT user_unique_login UNIQUE (login);
