CREATE OR REPLACE TABLE CAR (ID NUMBER PRIMARY KEY NOT NULL, "year" int NOT NULL, license_plate VARCHAR(200) NOT NULL, model VARCHAR(200) NOT NULL, color VARCHAR(200) NOT NULL);
CREATE OR REPLACE TABLE "USER" (ID NUMBER PRIMARY KEY NOT NULL, first_name VARCHAR(200) NOT NULL, last_name VARCHAR(200) NOT NULL, email VARCHAR(200) NOT NULL, birthday VARCHAR(200) NOT NULL, login VARCHAR(200) NOT NULL, password VARCHAR(200) NOT NULL, phone VARCHAR(200) NOT NULL, car_id int, FOREIGN KEY (car_id) REFERENCES car(id));

CREATE SEQUENCE SEQ_CAR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;